[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "AHM6e9HvhabUTBGub9AuZZjNcNkTfZrmXxEvCp1NmTRd"
[programs.devnet]
counter = "AHM6e9HvhabUTBGub9AuZZjNcNkTfZrmXxEvCp1NmTRd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/work/solana-book/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
