[package]
name = "procedural_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_demo = { path = "../macro_demo" }
macro_demo_derive = { path = "../macro_demo/macro_demo_derive" }