[package]
name = "rust_ping"
version = "0.1.0"
authors = ["chendan <chendan@tenxcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
serde = "1.0"
derive = "1.0"
serde_derive = "1.0"