#cargo-features = ["edition2021"]

[package]
name = "commandline"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt= "0.3.26"
colored = "2.0.0"
clap = "2.34.0"
