[book]
authors = ["Zicklag"]
multilingual = false
src = "book"
title = "Rust Tutorials"

[build]
build-dir = "build/book"

[output.html]
git_repository_url = "https://github.com/zicklag/rust-tutorials"
