[package]
name = "rust_primer"
version = "0.0.1"
edition = "2018"

[dependencies]
mongodb = { version = "2.5.0" }
tokio = "1.28.0"
chrono = "0.4.11"
serde = "1.0.105"
serde_json = "1.0.53"
bson = "2.6.1"
