[package]
name = "pestast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest_derive = "2.0"
pest = "=2.3"
pest-ast = "0.3.3"
from-pest = "0.3.1"
lazy_static = "1.3.0"