[package]
name = "mutexguard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thread-priority = "0.9.2"
thread-amount = "0.1.3"
crossbeam = "0.8.2"
thread-control = "0.1.2"