[features]
seeds = false
[programs.localnet]
postfeedapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
postfeedapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/work/solana-book/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
