[package]
name = "nonblocking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio="1.29.1"
futures = "0.3.5"
futures-timer = "3.0.2"
warp = "0.3"